// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gfdemo/internal/dao/internal"
)

// internalSchoolDao is internal type for wrapping internal DAO implements.
type internalSchoolDao = *internal.SchoolDao

// schoolDao is the data access object for table school.
// You can define custom methods on it to extend its functionality as you wish.
type schoolDao struct {
	internalSchoolDao
}

var (
	// School is globally public accessible object for table school operations.
	School = schoolDao{
		internal.NewSchoolDao(),
	}
)

// Fill with you ideas below.
